-- Vendas atribuídas a vendedores.
--
-- "Cliente" = empresa (public.company_profiles). O vendedor da venda sai de
-- company_profiles.sold_by (o vínculo cliente->vendedor, definido no cadastro
-- e congelado pelo gatilho de sales_reps.sql).
--
-- Duas origens:
--   * manual: o suporte lança pelo painel (admin_register_sale).
--   * payment: quando o Mercado Pago estiver ligado, um gatilho em
--     public.payments cria a venda automaticamente ao aprovar o pagamento.
--
-- Depende de sales_reps.sql e close_coin_purchases.sql. Idempotente.

create extension if not exists "pgcrypto";

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  seq bigint generated by default as identity,
  company_id uuid references public.company_profiles(id) on delete set null,
  company_name text,
  sales_rep_id uuid references public.sales_reps(id) on delete set null,
  sales_rep_code text,
  plan text not null,
  amount_cents integer not null default 0 check (amount_cents >= 0),
  payment_method text,
  payment_status text not null default 'pago'
    check (payment_status in ('pago', 'pendente', 'estornado', 'cancelado')),
  status text not null default 'confirmada'
    check (status in ('confirmada', 'pendente', 'cancelada')),
  source text not null default 'manual' check (source in ('manual', 'payment')),
  external_ref text,
  sold_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sales_sales_rep_id_idx on public.sales (sales_rep_id, sold_at desc);
create index if not exists sales_company_id_idx on public.sales (company_id);
create unique index if not exists sales_external_ref_key on public.sales (external_ref) where external_ref is not null;

drop trigger if exists sales_updated_at on public.sales;
create trigger sales_updated_at before update on public.sales
for each row execute function public.set_updated_at();

alter table public.sales enable row level security;

drop policy if exists "sales support read" on public.sales;
create policy "sales support read" on public.sales for select
using (public.is_support_user());

-- o vendedor lê só as próprias vendas
drop policy if exists "sales self read" on public.sales;
create policy "sales self read" on public.sales for select
using (
  exists (
    select 1 from public.sales_reps r
    where r.id = public.sales.sales_rep_id and r.user_id = auth.uid()
  )
);

-- --- Admin ------------------------------------------------------------

create or replace function public.admin_list_sales()
returns setof public.sales
language sql
security definer
stable
set search_path = public
as $$
  select * from public.sales
  where public.is_support_user()
  order by sold_at desc, seq desc
$$;

create or replace function public.admin_register_sale(
  p_company_id uuid,
  p_plan text,
  p_amount_cents integer,
  p_payment_method text,
  p_payment_status text,
  p_sold_at date
)
returns public.sales
language plpgsql
security definer
set search_path = public
as $$
declare
  sale public.sales;
  company public.company_profiles;
  rep public.sales_reps;
begin
  if not public.is_support_user() then
    raise exception 'Ação restrita ao suporte.';
  end if;
  if trim(coalesce(p_plan, '')) = '' then
    raise exception 'Informe o plano.';
  end if;

  select * into company from public.company_profiles where id = p_company_id;
  if not found then raise exception 'Empresa não encontrada.'; end if;

  if company.sold_by is not null and company.sold_by <> '' then
    select * into rep from public.sales_reps where upper(code) = upper(company.sold_by) limit 1;
  end if;

  insert into public.sales (
    company_id, company_name, sales_rep_id, sales_rep_code,
    plan, amount_cents, payment_method, payment_status, status, source, sold_at
  ) values (
    company.id, company.establishment_name, rep.id, rep.code,
    trim(p_plan),
    greatest(coalesce(p_amount_cents, 0), 0),
    nullif(trim(coalesce(p_payment_method, '')), ''),
    coalesce(nullif(trim(coalesce(p_payment_status, '')), ''), 'pago'),
    'confirmada',
    'manual',
    coalesce(p_sold_at, current_date)
  )
  returning * into sale;
  return sale;
end;
$$;

create or replace function public.admin_delete_sale(sale_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_support_user() then
    raise exception 'Ação restrita ao suporte.';
  end if;
  delete from public.sales where id = sale_id;
end;
$$;

revoke all on function public.admin_list_sales() from public;
revoke all on function public.admin_register_sale(uuid, text, integer, text, text, date) from public;
revoke all on function public.admin_delete_sale(uuid) from public;
grant execute on function public.admin_list_sales() to authenticated;
grant execute on function public.admin_register_sale(uuid, text, integer, text, text, date) to authenticated;
grant execute on function public.admin_delete_sale(uuid) to authenticated;

-- --- Gancho automático a partir de public.payments (se a tabela existir) ---
-- Quando um pagamento de empresa é aprovado (credited vira true), registra a
-- venda e atribui ao vendedor da empresa. Fica dormente até os pagamentos
-- estarem ligados.

do $$
begin
  if to_regclass('public.payments') is null then
    raise notice 'public.payments ainda não existe — gancho de venda automática não instalado.';
    return;
  end if;

  execute $fn$
    create or replace function public.record_sale_from_payment()
    returns trigger
    language plpgsql
    security definer
    set search_path = public
    as $body$
    declare
      company public.company_profiles;
      rep public.sales_reps;
    begin
      if new.credited is not true or (old.credited is true) then
        return new;
      end if;
      if new.role <> 'empresa' then
        return new;
      end if;
      if exists (select 1 from public.sales where external_ref = new.id::text) then
        return new;
      end if;

      select * into company from public.company_profiles where user_id = new.user_id;
      if not found then return new; end if;

      if company.sold_by is not null and company.sold_by <> '' then
        select * into rep from public.sales_reps where upper(code) = upper(company.sold_by) limit 1;
      end if;

      insert into public.sales (
        company_id, company_name, sales_rep_id, sales_rep_code,
        plan, amount_cents, payment_method, payment_status, status, source, external_ref, sold_at
      ) values (
        company.id, company.establishment_name, rep.id, rep.code,
        coalesce(new.product_id, 'Plano'),
        coalesce(new.amount_cents, 0),
        'mercadopago', 'pago', 'confirmada', 'payment', new.id::text,
        coalesce(new.paid_at::date, current_date)
      );
      return new;
    end;
    $body$;
  $fn$;

  execute 'drop trigger if exists trg_record_sale_from_payment on public.payments';
  execute 'create trigger trg_record_sale_from_payment after update of credited on public.payments for each row execute function public.record_sale_from_payment()';
end $$;
