services:
  - type: web
    name: free-floripa
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SUPABASE_STATE_KEY
        sync: false
